//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicBro.Shell.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicBro.Shell.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string Button_About {
            get {
                return ResourceManager.GetString("Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Film Strip.
        /// </summary>
        internal static string Button_AddFlimStrip {
            get {
                return ResourceManager.GetString("Button_AddFlimStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tags.
        /// </summary>
        internal static string Button_AddTags {
            get {
                return ResourceManager.GetString("Button_AddTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Favorites.
        /// </summary>
        internal static string Button_AddToFavorites {
            get {
                return ResourceManager.GetString("Button_AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEANUP DATABASE.
        /// </summary>
        internal static string Button_CleanDB {
            get {
                return ResourceManager.GetString("Button_CleanDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Tags.
        /// </summary>
        internal static string Button_ClearAllTags {
            get {
                return ResourceManager.GetString("Button_ClearAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        internal static string Button_Email {
            get {
                return ResourceManager.GetString("Button_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT.
        /// </summary>
        internal static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        internal static string Button_ResetSettings {
            get {
                return ResourceManager.GetString("Button_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string Button_Settings {
            get {
                return ResourceManager.GetString("Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIDESHOW.
        /// </summary>
        internal static string Button_Slide {
            get {
                return ResourceManager.GetString("Button_Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP IMAGES HERE.
        /// </summary>
        internal static string DropImages {
            get {
                return ResourceManager.GetString("DropImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string Label_AdvancedSettings {
            get {
                return ResourceManager.GetString("Label_AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Tag Pane.
        /// </summary>
        internal static string Label_AlignTagPane {
            get {
                return ResourceManager.GetString("Label_AlignTagPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Label_Background {
            get {
                return ResourceManager.GetString("Label_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR ALL DATA.
        /// </summary>
        internal static string Label_ClearAllData {
            get {
                return ResourceManager.GetString("Label_ClearAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Path.
        /// </summary>
        internal static string Label_DBPath {
            get {
                return ResourceManager.GetString("Label_DBPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Settings.
        /// </summary>
        internal static string Label_FileSettings {
            get {
                return ResourceManager.GetString("Label_FileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGES.
        /// </summary>
        internal static string Label_Images {
            get {
                return ResourceManager.GetString("Label_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Count.
        /// </summary>
        internal static string Label_ImagesCount {
            get {
                return ResourceManager.GetString("Label_ImagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Types.
        /// </summary>
        internal static string Label_ImageTypes {
            get {
                return ResourceManager.GetString("Label_ImageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER.
        /// </summary>
        internal static string Label_OTHER {
            get {
                return ResourceManager.GetString("Label_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please let us know at:.
        /// </summary>
        internal static string Label_Please {
            get {
                return ResourceManager.GetString("Label_Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected tag?.
        /// </summary>
        internal static string Label_Prompt {
            get {
                return ResourceManager.GetString("Label_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan the directories in the local database and remove all orphaned thumbs:.
        /// </summary>
        internal static string Label_ScanMessage {
            get {
                return ResourceManager.GetString("Label_ScanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Favorites Only.
        /// </summary>
        internal static string Label_SearchFavoritesOnly {
            get {
                return ResourceManager.GetString("Label_SearchFavoritesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search In Description.
        /// </summary>
        internal static string Label_SearchInDescription {
            get {
                return ResourceManager.GetString("Label_SearchInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search In Tags.
        /// </summary>
        internal static string Label_SearchInTags {
            get {
                return ResourceManager.GetString("Label_SearchInTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH OPTIONS.
        /// </summary>
        internal static string Label_SEARCHOPTIONS {
            get {
                return ResourceManager.GetString("Label_SEARCHOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {}{0} Results found.
        /// </summary>
        internal static string Label_SearchResult {
            get {
                return ResourceManager.GetString("Label_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to view all images with the selected tag?.
        /// </summary>
        internal static string Label_SelectTagPrompt {
            get {
                return ResourceManager.GetString("Label_SelectTagPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        internal static string Label_SelectTheme {
            get {
                return ResourceManager.GetString("Label_SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using our product. We hope you find this software as useful as we do. Are there any features missing? Is there anything else you would like to see?.
        /// </summary>
        internal static string Label_Splash {
            get {
                return ResourceManager.GetString("Label_Splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAG.
        /// </summary>
        internal static string Label_Tag {
            get {
                return ResourceManager.GetString("Label_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Size.
        /// </summary>
        internal static string Label_TotalSize {
            get {
                return ResourceManager.GetString("Label_TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string Label_UserInterface {
            get {
                return ResourceManager.GetString("Label_UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add directory.
        /// </summary>
        internal static string Menu_AddDirectory {
            get {
                return ResourceManager.GetString("Menu_AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string Menu_ClearAll {
            get {
                return ResourceManager.GetString("Menu_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear FlimStrip.
        /// </summary>
        internal static string Menu_ClearFlimStrip {
            get {
                return ResourceManager.GetString("Menu_ClearFlimStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string Menu_DateModified {
            get {
                return ResourceManager.GetString("Menu_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _FILE.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tags.
        /// </summary>
        internal static string Menu_ManageTags {
            get {
                return ResourceManager.GetString("Menu_ManageTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Menu_Name {
            get {
                return ResourceManager.GetString("Menu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        internal static string Menu_Popularity {
            get {
                return ResourceManager.GetString("Menu_Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Database.
        /// </summary>
        internal static string Menu_RemoveFromDataBase {
            get {
                return ResourceManager.GetString("Menu_RemoveFromDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Menu_Size {
            get {
                return ResourceManager.GetString("Menu_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string Menu_Tutorial {
            get {
                return ResourceManager.GetString("Menu_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Menu_Type {
            get {
                return ResourceManager.GetString("Menu_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the entire film strip?.
        /// </summary>
        internal static string Message_ClearAll {
            get {
                return ResourceManager.GetString("Message_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Images.
        /// </summary>
        internal static string Titl_ShowImages {
            get {
                return ResourceManager.GetString("Titl_ShowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tag?.
        /// </summary>
        internal static string Title_Delete {
            get {
                return ResourceManager.GetString("Title_Delete", resourceCulture);
            }
        }
    }
}
